initial setup to check the artifacts

diff --git a/.github/workflows/cypress.yml b/.github/workflows/cypress.yml
--- a/.github/workflows/cypress.yml
+++ b/.github/workflows/cypress.yml
@@ -21,9 +21,8 @@ jobs:
       - name: Install Cypress
         run: npx cypress install
       - name: Run Cypress tests
-        run: npx cypress run 
-        continue-on-error: true
-
+        run: |
+          npx cypress run || echo "Cypress tests failed" 
 
       - name: Upload Cypress screenshots
         if: always()
